apiVersion: v1
kind: Pod
metadata:
  labels:
    run: libkrun-pod
  name: libkrun-pod
  annotations:
    run.oci.handler: "krun"
spec:
  runtimeClassName: crun-krun
  containers:
  - image: fedora:latest
    name: container
    stdin: true
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/kvm
      name: kvm
    command: ["tail", "-f", "/dev/null"]
  restartPolicy: Never
  volumes:
  - name: kvm
    hostPath:
      path: /dev/kvm

