apiVersion: v1
kind: Pod
metadata:
  labels:
    run: libkrun-pod
  name: libkrun-pod
  annotations:
    run.oci.handler: "krun"
spec:
  runtimeClassName: crun-krun
  containers:
  - image: fedora:latest
    name: container
    stdin: true
    tty: true
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
    securityContext:
      privileged: true
    command: ["bash"]
  restartPolicy: Never
